// Actual theme picker/CSS in an isolated DOM. No room, broker or native operations.
const fs=require('fs'),path=require('path'),assert=require('assert'),cp=require('child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),now=fs.readFileSync(root+'/party-final1.html','utf8'),old=cp.execFileSync('git',['show','07a24daefae4ffbf00ef480aecde571caa47b37c:party-final1.html'],{cwd:root,encoding:'utf8'});
const marker='/* ===== Theme + Bubble picker: sirf rang badalta hai';
function theme(s){const a=s.indexOf(marker);return s.slice(a,s.indexOf('</script>',a));}
function normalized(s){return s.replace(/\n\/\* WP_NEON_THEME_START[\s\S]*?\/\* WP_NEON_THEME_END \*\/\n/,'').replace(/\n\/\* WP_FOUR_THEME_START[\s\S]*?\/\* WP_FOUR_THEME_END \*\//,'').replace(theme(s),'THEME').replace(/2026-10-06-(50|51|52)/g,'2026-10-06-49');}
assert.equal(normalized(now),normalized(old),'Any non-theme HTML/text/logic edit is forbidden');
const addCss=now.match(/\/\* WP_NEON_THEME_START[\s\S]*?\/\* WP_NEON_THEME_END \*\//)[0];
for(const body of addCss.matchAll(/\{([^}]+)\}/g))for(const declaration of body[1].split(';')){if(!declaration.trim())continue;assert(['background','color','border-color','box-shadow'].includes(declaration.split(':')[0].trim()),'Only paint properties allowed');}
function fixture(source){return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+source.match(/<style>([\s\S]*?)<\/style>/)[1]+'html:root :is(#theme-test-unused, *){animation:none!important;transition:none!important}</style></head><body><div class="join-card"><h1>Watch Party</h1><input placeholder="Original text"><button id="queue-btn">Queue</button></div><div id="wp-theme-grid"></div><div id="wp-bub-grid"></div><div id="wp-tb-name"></div><div id="wp-tb-sw"></div><div id="wp-ov"></div><div id="wp-sheet"></div><button id="wp-sh-x"></button><button id="wp-done"></button><div id="chat-messages"><div class="msg own"><div class="bubble" id="own">Original own message</div></div><div class="msg other"><div class="bubble" id="other">Original other message</div></div></div><div id="dm-thread" data-wallpaper="moon" style="background-image:url(assets/wallpaper-moon.svg);background-size:300px 300px"><div class="dm-m own"><div class="bub4" id="dm-own">Original DM message</div></div><div class="dm-m"><div class="bub4" id="dm-other">Original incoming message</div></div></div><div class="dm-row" id="friend-card"><div class="in3"><b>Friend</b><s>Original last message</s></div></div><button class="dm-call-action dm-call-answer">Answer</button><button class="dm-call-action dm-call-decline">Decline</button><script>'+theme(source)+'</script></body></html>';}

const previous=cp.execFileSync('git',['show','d5c797cca30e761d7c76a512c90088e36e71e265:party-final1.html'],{cwd:root,encoding:'utf8'});
const fourCss=now.match(/\/\* WP_FOUR_THEME_START[\s\S]*?\/\* WP_FOUR_THEME_END \*\//)[0];
for(const rule of fourCss.matchAll(/\{([^}]+)\}/g))for(const declaration of rule[1].split(';'))if(declaration.trim())assert(['background','color','border-color','box-shadow'].includes(declaration.split(':')[0].trim()));
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});let count=0;
async function make(size,seed={}){const c=await browser.newContext({viewport:size});await c.addInitScript(data=>{if(!sessionStorage.getItem('seeded')){for(const [k,v] of Object.entries(data))localStorage.setItem(k,v);sessionStorage.setItem('seeded','1')}},seed);await c.route('https://theme.test/**',r=>r.fulfill({contentType:'text/html',body:fixture(r.request().url().includes('previous')?previous:now)}));return c;}
async function choose(p,kind,key){await p.locator(`[data-kind="${kind}"][data-k="${key}"]`).evaluate(e=>e.click());}
async function snapshot(p){return p.evaluate(()=>['own','other','dm-own','dm-other','friend-card'].map(id=>{let e=document.getElementById(id),s=getComputedStyle(e),r=e.getBoundingClientRect();return {id,w:r.width,h:r.height,font:s.font,padding:s.padding,radius:s.borderRadius,text:e.textContent,bg:s.background,color:s.color,shadow:s.boxShadow}}));}
const labels={blue:'Ocean Cyan',emerald:'Emerald Glow',sunset:'Sunset Rose',amoled:'Champagne Gold'};
for(const size of [{width:344,height:727},{width:390,height:844},{width:768,height:1024},{width:1024,height:768}]){
 const c=await make(size),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('https://theme.test/new');assert.equal(await p.locator('[data-kind="t"]').count(),6);const original=await snapshot(p),colors=new Set();const wall=await p.locator('#dm-thread').getAttribute('style');const semantic=await p.locator('.dm-call-action').evaluateAll(es=>es.map(e=>getComputedStyle(e).background));
 for(const [key,label] of Object.entries(labels)){
  assert((await p.locator(`[data-kind="t"][data-k="${key}"]`).textContent()).includes(label));await choose(p,'t',key);assert.equal(await p.locator('html').getAttribute('data-wp-bubble'),key);let applied=await snapshot(p);colors.add(applied[0].bg);
  for(let i=0;i<original.length;i++)for(const k of ['w','h','font','padding','radius','text'])assert.equal(applied[i][k],original[i][k],key+' '+k);
  assert.equal(await p.locator('#dm-thread').getAttribute('style'),wall);assert.deepEqual(await p.locator('.dm-call-action').evaluateAll(es=>es.map(e=>getComputedStyle(e).background)),semantic);
  await p.reload();assert.equal(await p.locator('html').getAttribute('data-wp-theme'),key);assert.equal(await p.locator('html').getAttribute('data-wp-bubble'),key);await choose(p,'t','purple');assert.deepEqual(await snapshot(p),original);count++;
 }
 assert.equal(colors.size,4);await choose(p,'b','gm');for(const key of Object.keys(labels))await choose(p,'t',key);await p.reload();await choose(p,'t','neon');assert.equal(await p.locator('html').getAttribute('data-wp-bubble'),'neon');await choose(p,'t','purple');assert.equal(await p.locator('html').getAttribute('data-wp-bubble'),'gm');
 // Explicit standalone matching-bubble selection remains a valid preference.
 await choose(p,'b','blue');await choose(p,'t','emerald');await choose(p,'t','purple');assert.equal(await p.locator('html').getAttribute('data-wp-bubble'),'blue');assert.deepEqual(errors,[]);await c.close();
}
for(const key of Object.keys(labels)){const c=await make({width:390,height:844},{wp_theme:key,wp_bubble:'ob'}),p=await c.newPage();await p.goto('https://theme.test/new');assert.equal(await p.locator('html').getAttribute('data-wp-theme'),key);assert.equal(await p.locator('html').getAttribute('data-wp-bubble'),key);await choose(p,'b','gm');await p.reload();assert.equal(await p.locator('html').getAttribute('data-wp-bubble'),'gm','Migration must not reset explicit choices on every load');await choose(p,'t','purple');assert.equal(await p.locator('html').getAttribute('data-wp-bubble'),'gm');await c.close();}
for(const [t,b] of [['neon','neon'],['purple','now']]){const c=await make({width:390,height:844},{wp_theme:t,wp_bubble:b}),p=await c.newPage();await p.goto('https://theme.test/previous');const before=await snapshot(p);await p.goto('https://theme.test/new');assert.deepEqual(await snapshot(p),before,t+' must not change');assert.equal(await p.locator('html').getAttribute('data-wp-theme'),t);await c.close();}
await browser.close();console.log('PASS '+count+' four-theme viewport suites; six-card replacement, matching bubbles, persistence, default rollback, custom choices, once-only saved-theme migration, exact Neon/Purple parity, shared wallpapers, semantic call colors, paint-only scope.');})().catch(e=>{console.error(e);process.exit(1)});
