// Actual theme picker/CSS in an isolated DOM. No room, broker or native operations.
const fs=require('fs'),path=require('path'),assert=require('assert'),cp=require('child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),now=fs.readFileSync(root+'/party-final1.html','utf8'),old=cp.execFileSync('git',['show','07a24daefae4ffbf00ef480aecde571caa47b37c:party-final1.html'],{cwd:root,encoding:'utf8'});
const marker='/* ===== Theme + Bubble picker: sirf rang badalta hai';
function theme(s){const a=s.indexOf(marker);return s.slice(a,s.indexOf('</script>',a));}
function normalized(s){return s.replace(/\n\/\* WP_NEON_THEME_START[\s\S]*?\/\* WP_NEON_THEME_END \*\/\n/,'').replace(theme(s),'THEME').replaceAll('2026-10-06-50','2026-10-06-49');}
assert.equal(normalized(now),normalized(old),'Any non-theme HTML/text/logic edit is forbidden');
const addCss=now.match(/\/\* WP_NEON_THEME_START[\s\S]*?\/\* WP_NEON_THEME_END \*\//)[0];
for(const body of addCss.matchAll(/\{([^}]+)\}/g))for(const declaration of body[1].split(';')){if(!declaration.trim())continue;assert(['background','color','border-color','box-shadow'].includes(declaration.split(':')[0].trim()),'Only paint properties allowed');}
function fixture(source){return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+source.match(/<style>([\s\S]*?)<\/style>/)[1]+'*{animation:none!important;transition:none!important}</style></head><body><div class="join-card"><h1>Watch Party</h1><input placeholder="Original text"><button id="queue-btn">Queue</button></div><div id="wp-theme-grid"></div><div id="wp-bub-grid"></div><div id="wp-tb-name"></div><div id="wp-tb-sw"></div><div id="wp-ov"></div><div id="wp-sheet"></div><button id="wp-sh-x"></button><button id="wp-done"></button><div id="chat-messages"><div class="msg own"><div class="bubble" id="own">Original own message</div></div><div class="msg other"><div class="bubble" id="other">Original other message</div></div></div><div id="dm-thread" data-wallpaper="moon" style="background-image:url(assets/wallpaper-moon.svg);background-size:300px 300px"><div class="dm-m own"><div class="bub4" id="dm-own">Original DM message</div></div><div class="dm-m"><div class="bub4" id="dm-other">Original incoming message</div></div></div><div class="dm-row" id="friend-card"><div class="in3"><b>Friend</b><s>Original last message</s></div></div><button class="dm-call-action dm-call-answer">Answer</button><button class="dm-call-action dm-call-decline">Decline</button><script>'+theme(source)+'</script></body></html>';}
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});let n=0;
for(const [width,height] of [[344,727],[390,844],[768,1024],[1024,768]]){
 const context=await b.newContext({viewport:{width,height}});await context.route('https://theme.test/**',r=>r.fulfill({contentType:'text/html',body:fixture(r.request().url().includes('/old')?old:now)}));
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const state=()=>page.evaluate(()=>['own','other','dm-own','dm-other','friend-card'].map(id=>{const e=document.getElementById(id),s=getComputedStyle(e);return{id,text:e.textContent,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height,font:s.font,padding:s.padding,radius:s.borderRadius,bg:s.background,color:s.color,border:s.border,shadow:s.boxShadow}}));
 await page.goto('https://theme.test/old');const original=await state();
 await page.goto('https://theme.test/new');assert.deepEqual(await state(),original,'Default must be identical to live v49');
 const choose=async(kind,key)=>{await page.locator('.wp-card[data-kind="'+kind+'"][data-k="'+key+'"]').evaluate(e=>e.click());await page.waitForTimeout(400);};
 const wallpaper=await page.locator('#dm-thread').getAttribute('style');
 const callColors=await page.locator('.dm-call-action').evaluateAll(es=>es.map(e=>getComputedStyle(e).background));
 await choose('t','neon');assert.equal(await page.locator('html').getAttribute('data-wp-theme'),'neon');assert.equal(await page.locator('html').getAttribute('data-wp-bubble'),'neon');
 const neon=await state();for(let i=0;i<original.length;i++){for(const key of ['text','w','h','font','padding','radius'])assert.equal(neon[i][key],original[i][key],'No layout/text change '+key+' '+original[i].id);assert.notEqual(neon[i].bg,original[i].bg);}
 assert.equal(await page.locator('#dm-thread').getAttribute('style'),wallpaper,'Shared wallpaper cannot be replaced');assert.deepEqual(await page.locator('.dm-call-action').evaluateAll(es=>es.map(e=>getComputedStyle(e).background)),callColors,'Answer/decline semantics preserved');
 await page.reload();assert.equal(await page.locator('html').getAttribute('data-wp-theme'),'neon');
 await choose('t','purple');assert.equal(await page.locator('html').getAttribute('data-wp-bubble'),'now');{const restored=await state();if(JSON.stringify(restored)!==JSON.stringify(original))console.log(JSON.stringify({original,restored},null,2));assert.deepEqual(restored,original,'Single theme switch must restore original look');}
 await page.reload();assert.deepEqual(await state(),original,'Default return persists');
 await choose('b','ob');await choose('t','neon');await page.reload();await choose('t','purple');assert.equal(await page.locator('html').getAttribute('data-wp-bubble'),'ob','Previously selected bubble palette restored');
 await choose('t','neon');await choose('b','gm');await choose('t','blue');assert.equal(await page.locator('html').getAttribute('data-wp-bubble'),'gm','Explicit later bubble choice is respected');
 assert.deepEqual(errors,[]);n++;await context.close();
}
const context=await b.newContext();await context.addInitScript(()=>{Object.defineProperty(Storage.prototype,'getItem',{value(){throw Error('blocked')}});Object.defineProperty(Storage.prototype,'setItem',{value(){throw Error('blocked')}})});await context.route('https://theme.test/**',r=>r.fulfill({contentType:'text/html',body:fixture(now)}));const p=await context.newPage();await p.goto('https://theme.test/new');await p.locator('[data-kind="t"][data-k="neon"]').evaluate(e=>e.click());await p.locator('[data-kind="t"][data-k="purple"]').evaluate(e=>e.click());assert.equal(await p.locator('html').getAttribute('data-wp-bubble'),'now');await context.close();await b.close();console.log('PASS '+n+' viewport suites: exact default restoration, no geometry/text changes, persisted selection, custom-bubble restore, shared wallpapers, call status colors, blocked-storage safety, scoped paint-only CSS and untouched non-theme source.');})().catch(e=>{console.error(e);process.exit(1)});
